const companyStages = [
  "IDEA STAGE",
  "PRE SEED",
  "SEED",
  "PRE SERIES",
  "SERIES A+"
];

const industries = [
  "AUTOMOTIVE", "BANKING", "BROADCAST MEDIA", "COMPUTER & NETWORK SECURITY", "COMPUTER SOFTWARE",
  "CONSUMER ELECTRONICS", "CONSUMER GOODS", "CONSUMER SERVICES", "CIVIC & SOCIAL ORGANIZATION",
  "DEFENSE & SPACE", "EDUCATION MANAGEMENT", "ENTERTAINMENT", "E-LEARNING", "FINANCIAL SERVICES",
  "FOOD & BEVERAGES", "HEALTH", "HIGHER EDUCATION", "HOSPITAL & HEALTH CARE", "HUMAN RESOURCES",
  "INSURANCE", "INFORMATION TECHNOLOGY & SERVICES", "INTERNET", "INVESTMENT MANAGEMENT",
  "LEGAL SERVICES", "LEISURE", "LOGISTICS & SUPPLY CHAIN", "MANAGEMENT CONSULTING",
  "MARKETING & ADVERTISING", "MEDIA PRODUCTION", "NONPROFIT ORGANIZATION MANAGEMENT",
  "ONLINE MEDIA", "OUTSOURCING/OFFSHORING", "PROFESSIONAL TRAINING & COACHING",
  "PUBLIC RELATIONS & COMMUNICATIONS", "REAL ESTATE", "RETAIL", "STAFFING & RECRUITING",
  "TRANSLATION & LOCALIZATION", "VENTURE CAPITAL & PRIVATE EQUITY", "WELLNESS & FITNESS",
  "TRAVEL"
];

const sectors = [
  "AGTECH", "ARTIFICIAL INTELLIGENCE", "ARTIFICIAL REALITY", "AUTOMATION", "BANKING", "BIOTECH",
  "BLOCKCHAIN", "CLOUD COMPUTING", "CONSUMER ELECTRONICS", "CONSUMER GOODS", "CONSUMER INTERNET",
  "CONSUMER SERVICES", "CRYPTOCURRENCY", "DATA ANALYTICS", "DIGITAL HEALTH", "DIGITAL MEDIA",
  "DIGITAL TRANSFORMATION", "E-COMMERCE", "EDUCATION", "EDTECH", "ENTERPRISE SOFTWARE",
  "FASHION", "FINANCIAL SERVICES", "FOOD & BEVERAGE", "FOODTECH", "GAMING", "GOVTECH",
  "HEALTHCARE", "HEALTHTECH", "HARDWARE", "HOSPITALITY", "HUMAN RESOURCES", "INSURTECH",
  "INTERNET", "INTERNET OF THINGS (IOT)", "INVESTMENT MANAGEMENT", "LEGAL SERVICES",
  "LEGALTECH", "LOGISTICS", "MARKETPLACE", "MARKETING TECHNOLOGY", "MOBILE", "NONPROFIT",
  "NEUROTECH", "ONLINE MEDIA", "PROPTECH", "PUBLIC RELATIONS & COMMUNICATIONS", "REAL ESTATE",
  "REGTECH", "RETAIL", "ROBOTICS", "SAAS", "SECURITY", "SOCIAL NETWORK", "SUSTAINABILITY",
  "SUSTAINABILITY TECH", "TELECOMMUNICATIONS", "TRANSPORTATION", "TRAVEL",
  "VENTURE CAPITAL & PRIVATE EQUITY", "VIRTUAL REALITY", "WEB3"
];

const currentTraction = [
  "PRE PRODUCTION LAUNCH",
  "PRE REVENUE",
  "POST REVENUE",
  "BREAKEVEN"
];

const previousFunding = [
  "BOOTSTRAPPED",
  "ANGEL INVESTMENT",
  "PRE SEED",
  "SEED",
  "PRE SERIES",
  "SERIES A+"
];

const requiredFunding = [
  "< $100K",
  "$100K - $500K",
  "$500K - $1M",
  "$1M - $5M",
  ">$5M"]

export {
  companyStages,
  industries,
  sectors,
  currentTraction,
  previousFunding,
  requiredFunding,
};