import "./style.css"
import logo from "../../assets/logo.png";
import { useState } from "react";
import {useNavigate} from "react-router"
import FlowNav from "../../components/flowNavigation/component";

export default function Chat(){
    const navigate = useNavigate();
    const [selectedProfile, setSelectedProfile] = useState()
    const [pageno, setPage] = useState(0)
    
    const dummyData = [
      {
        name: "John Doe",
        nc: "JD",
        msg: "Seed-Stage AI Infrastructure",
        time: "9:30pm"
      },
      {
        name: "Chandra Sidhardha",
        nc: "CS",
        msg: "Seed-Stage AI Infrastructure",
        time: "9:40pm"
      },
    ];
    
    return (
      <div className="chatContainer">
        <FlowNav />
        <div className="topbar">
          <img src={logo} alt="" className="logo" />
          <p className="title">VERTX EMAILS</p>
        </div>
        <div className="sections">
          <div className="list">
            <p className="title" onClick={() => navigate("/generatemail")}>
              <ion-icon name="chevron-back-outline"></ion-icon>
              Emails
            </p>
            <div className="profiles">
              {dummyData?.map((profile) => (
                <div
                  className="profile"
                  onClick={() => setSelectedProfile(profile)}
                >
                  <div className="img">{profile.nc}</div>
                  <div className="details">
                    <p className="pname">{profile.name}</p>
                    <p className="pmsg">{profile.msg}..</p>
                  </div>
                  <p className="time">{profile.time}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="chatarea">
            {!selectedProfile ? (
              <>
                <ion-icon name="person"></ion-icon>
                <p className="big">- Select a Profile -</p>
                <p className="small">
                  Use Investor profiles to send professonal emails generated by
                  Vertx Flow
                </p>
              </>
            ) : (
              <div className="area">
                <div className="info">
                  <ion-icon
                    name="chevron-back-outline"
                    style={{ marginBottom: 0 }}
                  ></ion-icon>
                  <p className="name">John doe</p>
                </div>
                <div className="mails">
                  <div className="mail">
                    <p className="subject">
                      Seed-Stage AI Infrastructure Startup with Strong Metrics -
                      TechStartup Inc.Seed-Stage AI Infrastructure Startup with
                      Strong Metrics - TechStartup Inc.
                    </p>
                    <p className="body">
                      Dear Jane Smith, I hope this email finds you well. I
                      wanted to reach out to introduce you to TechStartup Inc.,
                      an AI infrastructure company that I founded and lead as
                      CEO. Our mission is to build next-generation AI
                      infrastructure that empowers businesses to leverage the
                      full potential of artificial intelligence and machine
                      learning. I was particularly drawn to VC Partners due to
                      your focus on AI and SaaS, and I believe that our company
                      aligns well with your stage preference of Seed and Series
                      A investments. I would like to share some of our recent
                      metrics with you: - Monthly Recurring Revenue (MRR): $50k
                      - Growth: 15% MoM - Customers: 100+. Our strong growth and
                      customer base demonstrate the market opportunity for our
                      AI infrastructure solutions. We are experiencing
                      increasing demand from businesses seeking to harness the
                      power of AI, and I am confident that our technology is
                      well-positioned to meet this need. I would be delighted to
                      schedule a call to discuss our company in more detail,
                      share our product roadmap, and answer any questions you
                      may have. Please let me know if this is of interest to
                      you. Thank you for considering TechStartup Inc. for
                      potential investment. I look forward to the opportunity to
                      speak with you soon. Best regards, John Doe TechStartup
                      Inc. CEO and Founder johndoe@techstartupinc.com (123)
                      456-7890
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    );
}